### PR TITLE
WIP: add support for local imports

### LINKED ISSUE #250: Macro annotation expansion of  @derive doesn't work having local imports of derevo.cats._
The following code doesn't compile on scala 2.13.5 (local import of derevo.cats._):

```
import cats.Monoid

object AnnotationProblem {
  import derevo.derive
  import derevo.cats.{eqv, monoid, order, show}

  @derive(eqv, show, order, monoid)
  case class ABC(
    a: String,
    b: Int,
    c: Boolean
  )

  val abcEmpty = Monoid[ABC].empty
}
```

Compilation error:
```
exception during macro expansion: 
scala.reflect.macros.TypecheckException: not found: value eqv
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
...
```

https://scastie.scala-lang.org/mbelikov/RARK4uYyRsuV3tEtvnOhIQ/4

Putting the import of derevo.cats._ to the global scope solves the compilation problem:
https://scastie.scala-lang.org/mbelikov/RARK4uYyRsuV3tEtvnOhIQ/6

The issue seems to be scala 2.13.x specific, for the 2.12 compiler the local import is ok:
https://scastie.scala-lang.org/mbelikov/RARK4uYyRsuV3tEtvnOhIQ/7

### PR DESCRIPTION
**Pull request by zawodskoj**
Closes #250

Compatibility with newtypes is not tested
This still won't work with pattern `object a { ... }; import a._` as this implementation does typechecking for each import statement that appears before `@derive` annotation
This implementation also uses deprecated enclosingTree API and may not work in future

### CODE REVIEW

**Comment by zawodskoj** [comment]
Closing as the implementation adds more pain than solves problem
