### ISSUE TITLE
Macro annotation expansion of  @derive doesn't work having local imports of derevo.cats._

### ISSUE THREAD

**Issue by mbelikov** [tofu-tf/derevo#250]
The following code doesn't compile on scala 2.13.5 (local import of derevo.cats._):

```
import cats.Monoid

object AnnotationProblem {
  import derevo.derive
  import derevo.cats.{eqv, monoid, order, show}

  @derive(eqv, show, order, monoid)
  case class ABC(
    a: String,
    b: Int,
    c: Boolean
  )

  val abcEmpty = Monoid[ABC].empty
}
```

Compilation error:
```
exception during macro expansion: 
scala.reflect.macros.TypecheckException: not found: value eqv
	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
...
```

https://scastie.scala-lang.org/mbelikov/RARK4uYyRsuV3tEtvnOhIQ/4

Putting the import of derevo.cats._ to the global scope solves the compilation problem:
https://scastie.scala-lang.org/mbelikov/RARK4uYyRsuV3tEtvnOhIQ/6

The issue seems to be scala 2.13.x specific, for the 2.12 compiler the local import is ok:
https://scastie.scala-lang.org/mbelikov/RARK4uYyRsuV3tEtvnOhIQ/7

**Comment by gvolpe** [comment]
@mbelikov that seems to be a weird issue but it works if you put the `derevo` imports at the top level instead of within the `object`. See https://scastie.scala-lang.org/bRlcYcdESwiAWb0ffGP0RA
